platform :ios ,'7.0'
  pod 'TouchJSON', '~> 1.1'
  pod 'RestKit', '~> 0.22.0'
  pod 'UIBubbleTableView', '~> 0.2'
  pod 'MagicalRecord', '~> 2.1'
  pod 'NSUserDefaults-AESEncryptor', '~> 0.0.3'
  pod 'FlatUIKit', '~> 1.2'
  pod 'DTAlertView', '~> 1.2.1'
  pod 'RTAlertView', '~> 0.0.5'
  pod 'Emoticonizer', '~> 1.0'
  pod 'NZAlertView', '~> 0.0.8'
  pod 'MWPhotoBrowser', '~> 1.2.1'
  pod 'CXPhotoBrowser', '~> 1.1.1'
pod 'Base64', '~> 1.0.1'
pod 'XMPPFramework', '~> 3.6.4'